---
- name: Add bash_profile_for_rbenv1
  sudo: no
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile

- name: Add bash_profile_for_rbenv2
  sudo: no
  shell: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  #shell: echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile

- name: Installs latest stable version of Ruby
  shell: rbenv install -s $(rbenv install -l | grep -v - | tail -1)
  register: result
  changed_when: '"Installed ruby" in result.stderr'

- name: Switch to latest stable version of Ruby
  shell: rbenv global $(rbenv install -l | grep -v - | tail -1)

- name: Installs latest available version of bundler.
  gem: name=bundler state=latest
